CREATE DATABASE QuanLyVatLieuXayDung;
GO


USE QuanLyVatLieuXayDung;
GO

-- USER
CREATE TABLE USERS(
	USERNAME NVARCHAR(50) NOT NULL
	CONSTRAINT PK_USERNAME PRIMARY KEY(USERNAME),
	PASSWORD VARCHAR(20),
	ROLE NVARCHAR(50)
);
GO


INSERT INTO USERS (USERNAME, PASSWORD, ROLE) 
VALUES
	('admin', 'admin', 'QL'),
	('nhanvien', 'nhanvien', 'NV')
GO


--MAIN
CREATE TABLE KHACHHANG (
    MAKHACH INT IDENTITY(1,1) PRIMARY KEY,
    TENKHACH NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    SDT VARCHAR(12) NOT NULL,
	FLAG BIT DEFAULT 0, -- Flag inactive
);
GO


CREATE TABLE NHACUNGCAP (
    MANCC INT IDENTITY(1,1) PRIMARY KEY,
    TENNCC NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    SDT VARCHAR(10) NOT NULL,	
	FLAG BIT DEFAULT 0, -- Flag inactive
);
GO


CREATE TABLE LOAIHANG (
    MALH INT IDENTITY(1,1) PRIMARY KEY,
    TENLOAI NVARCHAR(50) NOT NULL,
    DVT NVARCHAR(10) NOT NULL,
);
GO


CREATE TABLE SANPHAM (
    MASP INT IDENTITY(1,1) PRIMARY KEY,
    MALH INT NOT NULL,
    MANCC INT NULL,
	TENSP NVARCHAR(50) NOT NULL,
    GIA INT NOT NULL,
	FLAG BIT DEFAULT 0, -- Flag inactive
    FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);
GO


CREATE TABLE KHOHANG (
    MAKHO INT IDENTITY(1,1) PRIMARY KEY,
	TENKHOHANG NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(200) NOT NULL,
	SDTQUANLY VARCHAR(15) NULL,
);
GO


CREATE TABLE KHOHANGCHITIET (
    MAKHO INT NOT NULL,
    MASP INT NOT NULL,
    SOLUONG INT NOT NULL,
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	FOREIGN KEY (MAKHO) REFERENCES KHOHANG(MAKHO)
);
GO


CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1) PRIMARY KEY,
    MAKHACH INT NOT NULL,
	MAKHO INT NOT NULL,
    NGAYLAPHOADON DATE NOT NULL,
    LOAIHOADON NVARCHAR(10) NOT NULL,
    TRANGTHAI NVARCHAR(10) NOT NULL,
    FOREIGN KEY (MAKHACH) REFERENCES KHACHHANG(MAKHACH),
	FOREIGN KEY (MAKHO) REFERENCES KHOHANG(MAKHO)
);
GO


CREATE TABLE HOADONCHITIET (
    MASP INT NOT NULL,
    MAHD INT NOT NULL,
    SOLUONG INT NOT NULL,
    FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
    FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD)
);
GO


-- TRIGGER SANPHAM
CREATE OR ALTER TRIGGER trg_SANPHAM_insert
ON SANPHAM
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO SANPHAM (MALH, MANCC, TENSP, GIA)
    SELECT
		inserted.MALH,
        CASE WHEN inserted.MANCC = 0 THEN NULL ELSE inserted.MANCC END,
        inserted.TENSP,
        inserted.GIA
    FROM inserted;
END
GO


-- TRIGGER HOADON
CREATE OR ALTER TRIGGER trg_HOADON_Update
ON HOADON
AFTER UPDATE
AS
BEGIN
    IF UPDATE(TRANGTHAI)
    BEGIN
        -- Update KHOHANGCHITIET for the affected MAKHO
        UPDATE khct
        SET khct.SOLUONG = khct.SOLUONG + hdct.SOLUONG
        FROM KHOHANGCHITIET khct
        JOIN HOADONCHITIET hdct ON khct.MASP = hdct.MASP
        JOIN inserted i ON hdct.MAHD = i.MAHD
        WHERE i.TRANGTHAI = 'Success' AND i.LOAIHOADON = N'Nhập' AND khct.MAKHO = i.MAKHO
        
        -- Insert new rows into KHOHANGCHITIET for the affected MAKHO
        INSERT INTO KHOHANGCHITIET (MAKHO, MASP, SOLUONG)
        SELECT i.MAKHO, hdct.MASP, hdct.SOLUONG
        FROM HOADONCHITIET hdct
        JOIN inserted i ON hdct.MAHD = i.MAHD
        WHERE i.TRANGTHAI LIKE 'Success' AND i.LOAIHOADON LIKE N'Nhập' AND hdct.MASP NOT IN (
            SELECT MASP FROM KHOHANGCHITIET WHERE MAKHO = i.MAKHO
        )


		-- Update KHOHANGCHITIET for the affected MAKHO
        UPDATE khct
        SET khct.SOLUONG = khct.SOLUONG + hdct.SOLUONG
        FROM KHOHANGCHITIET khct
        JOIN HOADONCHITIET hdct ON khct.MASP = hdct.MASP
        JOIN inserted i ON hdct.MAHD = i.MAHD
        WHERE i.TRANGTHAI = 'Cancelled' AND i.LOAIHOADON = N'Xuất' AND khct.MAKHO = i.MAKHO
    END
END
GO

CREATE OR ALTER TRIGGER trg_HOADON_delete
ON HOADON
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @maHd INT = (SELECT MAHD FROM deleted)

	DELETE HOADONCHITIET
	WHERE MAHD = @maHd

	DELETE HOADON
	WHERE MAHD = @maHd
END
GO


-- TRIGGER HOADONCHITIET
CREATE OR ALTER TRIGGER trg_HOADONCHITIET_insert
ON HOADONCHITIET
AFTER INSERT
AS
BEGIN
    UPDATE khct
    SET khct.SOLUONG = khct.SOLUONG - i.SOLUONG
    FROM KHOHANGCHITIET khct
    JOIN inserted i ON khct.MASP = i.MASP
    JOIN HOADON hd ON i.MAHD = hd.MAHD
    WHERE hd.LOAIHOADON = N'Xuất' AND khct.MAKHO = hd.MAKHO;
END
GO

CREATE OR ALTER TRIGGER trg_HOADONCHITIET_update
ON HOADONCHITIET
INSTEAD OF UPDATE
AS
BEGIN
    -- Update KHOHANGCHITIET for 'Xuất' type of HOADON with 'Pending' status
    UPDATE khct
    SET khct.SOLUONG = khct.SOLUONG + (i.SOLUONG - d.SOLUONG)
    FROM KHOHANGCHITIET khct
    JOIN inserted i ON khct.MASP = i.MASP
    JOIN deleted d ON khct.MASP = d.MASP
    JOIN HOADON hd ON i.MAHD = hd.MAHD
    WHERE hd.LOAIHOADON = N'Xuất' AND hd.TRANGTHAI = 'Pending' AND khct.MAKHO = hd.MAKHO;

	-- Update KHOHANGCHITIET for 'Xuất' type of HOADON with 'Cancelled' status
	UPDATE khct
    SET khct.SOLUONG = khct.SOLUONG + d.SOLUONG
    FROM KHOHANGCHITIET khct
    JOIN inserted i ON khct.MASP = i.MASP
    JOIN deleted d ON khct.MASP = d.MASP
    JOIN HOADON hd ON i.MAHD = hd.MAHD
    WHERE hd.LOAIHOADON = N'Xuất' AND hd.TRANGTHAI = 'Cancelled' AND khct.MAKHO = hd.MAKHO;


    -- Update the HOADONCHITIET table with the new SOLUONG value
    UPDATE hdct
    SET hdct.SOLUONG = i.SOLUONG
    FROM HOADONCHITIET hdct
    JOIN inserted i ON hdct.MAHD = i.MAHD AND hdct.MASP = i.MASP;
END
GO

CREATE OR ALTER TRIGGER trg_HOADONCHITIET_delete
ON HOADONCHITIET
INSTEAD OF DELETE
AS
BEGIN
    -- Update KHOHANGCHITIET for 'Xuất' type of HOADON with 'Pending' status
    UPDATE khct
    SET khct.SOLUONG = khct.SOLUONG + d.SOLUONG
    FROM KHOHANGCHITIET khct
    JOIN deleted d ON khct.MASP = d.MASP
    JOIN HOADON h ON d.MAHD = h.MAHD
    WHERE h.LOAIHOADON = N'Xuất' AND h.TRANGTHAI = 'Pending' AND khct.MAKHO = h.MAKHO;

    -- Delete the row from HOADONCHITIET
    DELETE FROM HOADONCHITIET
    WHERE MAHD IN (SELECT MAHD FROM deleted) AND MASP IN (SELECT MASP FROM deleted);
END
GO


-- PROCEDURE DELETE HOADONCHTIET
CREATE OR ALTER PROCEDURE proc_ErrorHDCT
AS
BEGIN
    DELETE hdct
    FROM HOADONCHITIET hdct
    JOIN HOADON hd ON hdct.MAHD = hd.MAHD
    JOIN KHOHANG kh ON hd.MAKHO = kh.MAKHO
    LEFT JOIN KHOHANGCHITIET khct ON kh.MAKHO = khct.MAKHO AND hdct.MASP = khct.MASP
    WHERE hd.LOAIHOADON = N'Xuất'
        AND khct.MASP IS NULL;
END;
GO


/*
EXEC sp_MSforeachtable @command1 = "DROP TABLE ?"
*/